spring:
  application:
    name: server
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/Impulz

  datasource:
    url: jdbc:postgresql://localhost:5435/impulz
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8083
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: TRACE


keycloak:
   keycloakUrl: http://localhost:9090
   realm: Impulz
   clientId: ImpulzServer
   clientSecret: XwsMl50NUc8GEybyhMGtI7QejOPLeK8X


