spring:
  application:
    name: server
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/Impulz
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5435/impulz
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  url: http://localhost:8083
  port: 8083
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: TRACE

keycloak:
  keycloakUrl: http://localhost:9090
  realm: Impulz
  clientId: ImpulzServer
  clientSecret: PGI80PTF69TCx03xScxVm7JWNyowL6OD
  admin-username: admin
  admin-password: admin

aws:
  region: us-east-1
  s3:
    bucket-name: impulz-bucket-1
  accessKeyId: AKIAT7YEJYD37Q7ZO6EO
  secretKey: 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

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:impulz-bucket-1}
  region: us-east-1

music:
  base-url: https://impulz-bucket-1.s3.us-east-1.amazonaws.com/music/

app:
  temp-dir: ${java.io.tmpdir}/audio_uploads

jwt:
  secret: wI0Fcd3rZPL+CQ6X5koM0dn8CKV2gA3VX0Z0M4cV2Rk=