spring:
  application:
    name: server

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/impulz}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  elasticsearch:
    uris: ${ELASTICSEARCH_URL:http://localhost:9200}

  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:9090/realms/Impulz/protocol/openid-connect/certs}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    elasticsearch:
      repositories:
        enabled: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis

server:
  url: ${SERVER_URL:http://localhost:8083}
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG
    org.springframework.security: TRACE
    org.springframework.expression: DEBUG
    org.springframework.cache.interceptor: TRACE
    org.springframework.data.redis: DEBUG
    org.elasticsearch.client: DEBUG
    com.example.server: DEBUG
    org.springframework.web: DEBUG

keycloak:
  keycloakUrl: ${KEYCLOAK_URL:http://localhost:9090}
  realm: ${KEYCLOAK_REALM:Impulz}
  clientId: ${KEYCLOAK_CLIENT_ID:ImpulzServer}
  frontClientId: ${KEYCLOAK_FRONT_CLIENT_ID:ImpulzClient}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET:HbSOGYw4THGNmLUCjsa0iN9yjHVQd18H}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:impulz-bucket-1}
  region: us-east-1

music:
  base-url: ${MUSIC_BASE_URL:https://impulz-bucket-1.s3.us-east-1.amazonaws.com/music/}

app:
  frontend:
    cancel-url: ${FRONTEND_ERROR_URL:http://localhost:3000}
    success-url: ${FRONTEND_SUCCESS_URL:http://localhost:3000}
  temp-dir: ${java.io.tmpdir}/audio_uploads

jwt:
  secret: ${JWT_SECRET:wI0Fcd3rZPL+CQ6X5koM0dn8CKV2gA3VX0Z0M4cV2Rk=}

cloud:
  aws:
    s3:
      bucket: impulz-bucket-1
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION:us-east-1}

stripe:
  secret_key: ${STRIPE_SECRET_KEY}
  webhook_secret: ${STRIPE_WEBHOOK_SECRET}